CREATE TABLE `parksoft`.`parking_admins` (
  `ID_PARKING` INT NOT NULL,
  `ID_USERS` INT NOT NULL,
  PRIMARY KEY (`ID_PARKING`, `ID_USERS`),
  CONSTRAINT `FK_PARKING_ID_PARKING`
    FOREIGN KEY (`ID_PARKING`)
    REFERENCES `parksoft`.`parkings` (`ID_PARKING`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USERS_ID_USERS`
    FOREIGN KEY (`ID_USERS`)
    REFERENCES `parksoft`.`users` (`ID_USERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);