CREATE TABLE `parksoft`.`parkings` (
  `ID_PARKING` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `CANTIDAD` INT NOT NULL,
  `COSTO` DECIMAL(10,2) NOT NULL,
  `ENABLED` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID_PARKING`)
  );
  