CREATE TABLE `parksoft`.`users_roles` (
  `ID_USERS` INT NOT NULL,
  `ID_ROLES` INT NOT NULL,
  PRIMARY KEY (`ID_USERS`, `ID_ROLES`),
  CONSTRAINT `FK_USERS_ID_USER`
    FOREIGN KEY (`ID_USERS`)
    REFERENCES `parksoft`.`users` (`ID_USERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ROLES_ID_ROLES`
    FOREIGN KEY (`ID_ROLES`)
    REFERENCES `parksoft`.`roles` (`ID_ROLES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);