CREATE TABLE `parksoft`.`roles` (
  `ID_ROLES` INT NOT NULL AUTO_INCREMENT,
  `ROL` enum('ROLE_ADMIN','ROLE_SOCIO') NOT NULL,
  PRIMARY KEY (`ID_ROLES`),
  UNIQUE INDEX `ROLES_ROL_UNIQUE` (`ROL` ASC) VISIBLE);