CREATE TABLE `parksoft`.`users` (
  `ID_USERS` INT NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(254) NOT NULL,
  `PASSWORD` VARCHAR(80) NOT NULL,
  `ENABLED` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID_USERS`),
  UNIQUE INDEX `USERS_EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE);